// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/difficult-guest/DifficultGuest.tsx": () => import("../components/mockups/difficult-guest/DifficultGuest.tsx"),
  "./components/mockups/video-export/VideoExport.tsx": () => import("../components/mockups/video-export/VideoExport.tsx")
};
